### ISSUE TITLE
How to fix /dev/ppp

### ISSUE THREAD

**Issue by kapik** [ronamosa/forticlient-vpn#1]
Hi 👋 

I have this error on runtime: 

```ssh
STATUS::Login succeed
STATUS::Starting PPPd
STATUS::Initializing tunnel
STATUS::Connecting to server
/usr/sbin/pppd: You need to create the /dev/ppp device node by
executing the following command as root:
	mknod /dev/ppp c 108 0

STATUS::Connected
Press Ctrl-C to quit
```

Any suggestion to fix this ? 
Of course I tried to execute this command but I still get this error
Thanks 😃

**Comment by ronamosa** [comment]
apologies @kapik I am just seeing this issue now (I'm crap at checking messages). I hope you got it sorted in the end.
